//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carnac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnac uses.
        /// </summary>
        public static string About_CarnacUses {
            get {
                return ResourceManager.GetString("About_CarnacUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a code52 project.
        /// </summary>
        public static string About_Code52Project {
            get {
                return ResourceManager.GetString("About_Code52Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a project by.
        /// </summary>
        public static string About_ProjectBy {
            get {
                return ResourceManager.GetString("About_ProjectBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Carnac Website.
        /// </summary>
        public static string About_VisitWebsite {
            get {
                return ResourceManager.GetString("About_VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string Preferences_AutoUpdate {
            get {
                return ResourceManager.GetString("Preferences_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto check updates from GitHub (need to restart this program).
        /// </summary>
        public static string Preferences_AutoUpdateDescription {
            get {
                return ResourceManager.GetString("Preferences_AutoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string Preferences_BackgroundColor {
            get {
                return ResourceManager.GetString("Preferences_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Offset.
        /// </summary>
        public static string Preferences_BottomOffset {
            get {
                return ResourceManager.GetString("Preferences_BottomOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Radius.
        /// </summary>
        public static string Preferences_CornerRadius {
            get {
                return ResourceManager.GetString("Preferences_CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string Preferences_FontColor {
            get {
                return ResourceManager.GetString("Preferences_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string Preferences_FontFamily {
            get {
                return ResourceManager.GetString("Preferences_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string Preferences_FontSize {
            get {
                return ResourceManager.GetString("Preferences_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Preferences_Language {
            get {
                return ResourceManager.GetString("Preferences_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen Preferences to see this window in the new language..
        /// </summary>
        public static string Preferences_LanguageHint {
            get {
                return ResourceManager.GetString("Preferences_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string Preferences_LanguageSystemDefault {
            get {
                return ResourceManager.GetString("Preferences_LanguageSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Offset.
        /// </summary>
        public static string Preferences_LeftOffset {
            get {
                return ResourceManager.GetString("Preferences_LeftOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only keys with Modifiers.
        /// </summary>
        public static string Preferences_OnlyModifiers {
            get {
                return ResourceManager.GetString("Preferences_OnlyModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show keys that have Ctrl, Shift, Alt or Windows.
        /// </summary>
        public static string Preferences_OnlyModifiersDescription {
            get {
                return ResourceManager.GetString("Preferences_OnlyModifiersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Fade Delay (sec).
        /// </summary>
        public static string Preferences_PopupFadeDelay {
            get {
                return ResourceManager.GetString("Preferences_PopupFadeDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Opacity.
        /// </summary>
        public static string Preferences_PopupOpacity {
            get {
                return ResourceManager.GetString("Preferences_PopupOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Padding.
        /// </summary>
        public static string Preferences_PopupPadding {
            get {
                return ResourceManager.GetString("Preferences_PopupPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Text Width.
        /// </summary>
        public static string Preferences_PopupTextWidth {
            get {
                return ResourceManager.GetString("Preferences_PopupTextWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Filter.
        /// </summary>
        public static string Preferences_ProcessFilter {
            get {
                return ResourceManager.GetString("Preferences_ProcessFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show keys from processes matching this regular expression.
        /// </summary>
        public static string Preferences_ProcessFilterDescription {
            get {
                return ResourceManager.GetString("Preferences_ProcessFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string Preferences_ResetToDefaults {
            get {
                return ResourceManager.GetString("Preferences_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Offset.
        /// </summary>
        public static string Preferences_RightOffset {
            get {
                return ResourceManager.GetString("Preferences_RightOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Preferences_Save {
            get {
                return ResourceManager.GetString("Preferences_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts Only.
        /// </summary>
        public static string Preferences_ShortcutsOnly {
            get {
                return ResourceManager.GetString("Preferences_ShortcutsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show keys that are listed in the Keymaps folder.
        /// </summary>
        public static string Preferences_ShortcutsOnlyDescription {
            get {
                return ResourceManager.GetString("Preferences_ShortcutsOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Application Icon.
        /// </summary>
        public static string Preferences_ShowApplicationIcon {
            get {
                return ResourceManager.GetString("Preferences_ShowApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the active application&apos;s icon.
        /// </summary>
        public static string Preferences_ShowApplicationIconDescription {
            get {
                return ResourceManager.GetString("Preferences_ShowApplicationIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Space as ␣.
        /// </summary>
        public static string Preferences_ShowSpaceAsUnicode {
            get {
                return ResourceManager.GetString("Preferences_ShowSpaceAsUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Space as Unicode character &apos;␣&apos;.
        /// </summary>
        public static string Preferences_ShowSpaceAsUnicodeDescription {
            get {
                return ResourceManager.GetString("Preferences_ShowSpaceAsUnicodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string Preferences_SystemDefaultFont {
            get {
                return ResourceManager.GetString("Preferences_SystemDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Preferences_TabAbout {
            get {
                return ResourceManager.GetString("Preferences_TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Preferences_TabAppearance {
            get {
                return ResourceManager.GetString("Preferences_TabAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Preferences_TabGeneral {
            get {
                return ResourceManager.GetString("Preferences_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Offset.
        /// </summary>
        public static string Preferences_TopOffset {
            get {
                return ResourceManager.GetString("Preferences_TopOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ShellView_Exit {
            get {
                return ResourceManager.GetString("ShellView_Exit", resourceCulture);
            }
        }
    }
}
