//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carnac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ShellView_Exit {
            get {
                return ResourceManager.GetString("ShellView_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string TrayMenu_Pause {
            get {
                return ResourceManager.GetString("TrayMenu_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart as administrator.
        /// </summary>
        internal static string TrayMenu_RestartAsAdministrator {
            get {
                return ResourceManager.GetString("TrayMenu_RestartAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string TrayMenu_Resume {
            get {
                return ResourceManager.GetString("TrayMenu_Resume", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        internal static string TrayMenu_Settings {
            get {
                return ResourceManager.GetString("TrayMenu_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Silent mode.
        /// </summary>
        internal static string TrayMenu_SilentMode {
            get {
                return ResourceManager.GetString("TrayMenu_SilentMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string TrayStatus_Paused {
            get {
                return ResourceManager.GetString("TrayStatus_Paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to silent mode.
        /// </summary>
        internal static string TrayStatus_Silent {
            get {
                return ResourceManager.GetString("TrayStatus_Silent", resourceCulture);
            }
        }
    }
}
